apiVersion: v1
kind: Service

metadata:
  name: relationship-manager
  namespace: emortalmc

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: relationship-manager
